add purge_quadlet_dir param
voxpupuli/puppet-quadlets pull request #17
Opened 2024-09-17 22:40 UTC by jhoblitt

2024-09-17 22:42 UTC, jhoblitt commented
I'm guessing F40 is broken everywhere?

2024-09-18 16:51 UTC, traylenator requested changes

2024-09-18 16:51 UTC, traylenator commented on manifests/config.pp
> +      purge   => $quadlets::purge_quadlet_dir,
Can we be consistent with the existing variables and set them local in this class.

2024-09-18 17:20 UTC, jhoblitt commented on manifests/config.pp
> +      purge   => $quadlets::purge_quadlet_dir,
I'm generally not a fan of using inheritance for passing internal data but OK.  Note that `quadlets::quadlet` will still have to directly to the variable in `quadlets`.

2024-09-19 19:51 UTC, traylenator commented
Tomorrow.

2024-09-20 06:30 UTC, traylenator approved these changes

2024-09-20 15:47 UTC, merged