Add Kube type quadlet support
voxpupuli/puppet-quadlets pull request #5
Opened 2024-07-08 13:53 UTC by dabelenda

2024-07-08 14:05 UTC, dabelenda commented
Will rebase when tests are fixed on https://github.com/voxpupuli/puppet-quadlets/pull/4

2024-08-19 09:12 UTC, dabelenda commented
@traylenator is it possible to have a review ?

2024-08-20 13:12 UTC, traylenator requested changes

2024-08-20 13:12 UTC, traylenator commented on manifests/quadlet.pp
> +#     kube_entry => {
I've never use kube like entries so am learning here.

I think this example would fail since you would run into: 

```
if $volume_entry or $pod_entry or $container_entry {
        fail('A container_entry, pod_entry or volume_entry makes no sense on a kube quadlet')
}
```

Create a new second kube example makes sense.

2024-08-23 05:50 UTC, dabelenda commented on manifests/quadlet.pp
> +#     kube_entry => {
I didn't realize that when I edited the manifest...

I created a new example for running a pod using kubernetes yaml.

2024-08-23 09:14 UTC, traylenator requested changes

2024-08-23 09:14 UTC, traylenator commented on manifests/quadlet.pp
> +#   file { '/path/to/yaml/file',
Get rid of this `file{ '/path ... `  don't think it adds anything useful.

2024-08-23 09:14 UTC, traylenator commented on manifests/quadlet.pp
> +#       'Yaml' => '/path/to/yaml/file',
```suggestion
#       'Yaml' => '/path/to/yaml/file.yaml',
```

2024-08-23 09:38 UTC, dabelenda commented on manifests/quadlet.pp
> +#       'Yaml' => '/path/to/yaml/file',
Added the extension

2024-08-23 09:38 UTC, dabelenda commented on manifests/quadlet.pp
> +#   file { '/path/to/yaml/file',
removed the file definition

2024-08-23 09:50 UTC, traylenator approved these changes

2024-08-25 08:54 UTC, merged